CREATE TABLE `video_events` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer,
	`teacher` text NOT NULL,
	`student` text NOT NULL,
	`course_id` integer NOT NULL,
	`lesson_id` integer NOT NULL,
	`video_id` text NOT NULL,
	`session_id` text NOT NULL,
	`event` text NOT NULL,
	`current_time` real NOT NULL,
	`duration` real NOT NULL,
	`seek_from` real,
	`seek_to` real,
	`playback_rate` real,
	`volume` integer,
	`muted` integer,
	`device` text,
	`browser` text,
	`os` text,
	`ip` text,
	`country` text
);
